### ISSUE TITLE
'Worker Class Not Found'

### ISSUE THREAD

**Issue by QRX53** [kbinani/je2be-web#1]
Any time I try to upload my world, I get hit with a 'Worker class not found' error, any idea what to do?

**Comment by kbinani** [comment]
@44-million I suspect that your browser doesn't support launching a Worker nested in a Worker.
Are you using Safari in macOS, or another browser in iOS?
If so, please consider using iOS version of je2be: https://apps.apple.com/us/app/je2be/id1617552608
